// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: github_provider.proto

package github_provider

import (
	_ "github.com/clubcedille/calidum-rotae-backend/pkg/proto-gen/provider"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchPRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUID       string                 `protobuf:"bytes,1,opt,name=UserUID,proto3" json:"UserUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPRRequest) Reset() {
	*x = FetchPRRequest{}
	mi := &file_github_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPRRequest) ProtoMessage() {}

func (x *FetchPRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPRRequest.ProtoReflect.Descriptor instead.
func (*FetchPRRequest) Descriptor() ([]byte, []int) {
	return file_github_provider_proto_rawDescGZIP(), []int{0}
}

func (x *FetchPRRequest) GetUserUID() string {
	if x != nil {
		return x.UserUID
	}
	return ""
}

type FetchPRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPRResponse) Reset() {
	*x = FetchPRResponse{}
	mi := &file_github_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPRResponse) ProtoMessage() {}

func (x *FetchPRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPRResponse.ProtoReflect.Descriptor instead.
func (*FetchPRResponse) Descriptor() ([]byte, []int) {
	return file_github_provider_proto_rawDescGZIP(), []int{1}
}

var File_github_provider_proto protoreflect.FileDescriptor

const file_github_provider_proto_rawDesc = "" +
	"\n" +
	"\x15github_provider.proto\x12\x0fgithub_provider\x1a\x0eprovider.proto\"*\n" +
	"\x0eFetchPRRequest\x12\x18\n" +
	"\aUserUID\x18\x01 \x01(\tR\aUserUID\"\x11\n" +
	"\x0fFetchPRResponse2^\n" +
	"\x0eGithubProvider\x12L\n" +
	"\aFetchPR\x12\x1f.github_provider.FetchPRRequest\x1a .github_provider.FetchPRResponseB\\ZZgithub.com/clubcedille/calidum-rotae-backend/pkg/proto-gen/github-provider;github_providerb\x06proto3"

var (
	file_github_provider_proto_rawDescOnce sync.Once
	file_github_provider_proto_rawDescData []byte
)

func file_github_provider_proto_rawDescGZIP() []byte {
	file_github_provider_proto_rawDescOnce.Do(func() {
		file_github_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_provider_proto_rawDesc), len(file_github_provider_proto_rawDesc)))
	})
	return file_github_provider_proto_rawDescData
}

var file_github_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_provider_proto_goTypes = []any{
	(*FetchPRRequest)(nil),  // 0: github_provider.FetchPRRequest
	(*FetchPRResponse)(nil), // 1: github_provider.FetchPRResponse
}
var file_github_provider_proto_depIdxs = []int32{
	0, // 0: github_provider.GithubProvider.FetchPR:input_type -> github_provider.FetchPRRequest
	1, // 1: github_provider.GithubProvider.FetchPR:output_type -> github_provider.FetchPRResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_provider_proto_init() }
func file_github_provider_proto_init() {
	if File_github_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_provider_proto_rawDesc), len(file_github_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_provider_proto_goTypes,
		DependencyIndexes: file_github_provider_proto_depIdxs,
		MessageInfos:      file_github_provider_proto_msgTypes,
	}.Build()
	File_github_provider_proto = out.File
	file_github_provider_proto_goTypes = nil
	file_github_provider_proto_depIdxs = nil
}
