// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: github_provider.proto

package github_provider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GithubProvider_FetchPR_FullMethodName = "/github_provider.GithubProvider/FetchPR"
)

// GithubProviderClient is the client API for GithubProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GithubProviderClient interface {
	// Get User pull requests
	FetchPR(ctx context.Context, in *FetchPRRequest, opts ...grpc.CallOption) (*FetchPRResponse, error)
}

type githubProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewGithubProviderClient(cc grpc.ClientConnInterface) GithubProviderClient {
	return &githubProviderClient{cc}
}

func (c *githubProviderClient) FetchPR(ctx context.Context, in *FetchPRRequest, opts ...grpc.CallOption) (*FetchPRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchPRResponse)
	err := c.cc.Invoke(ctx, GithubProvider_FetchPR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GithubProviderServer is the server API for GithubProvider service.
// All implementations must embed UnimplementedGithubProviderServer
// for forward compatibility.
type GithubProviderServer interface {
	// Get User pull requests
	FetchPR(context.Context, *FetchPRRequest) (*FetchPRResponse, error)
	mustEmbedUnimplementedGithubProviderServer()
}

// UnimplementedGithubProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGithubProviderServer struct{}

func (UnimplementedGithubProviderServer) FetchPR(context.Context, *FetchPRRequest) (*FetchPRResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchPR not implemented")
}
func (UnimplementedGithubProviderServer) mustEmbedUnimplementedGithubProviderServer() {}
func (UnimplementedGithubProviderServer) testEmbeddedByValue()                        {}

// UnsafeGithubProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GithubProviderServer will
// result in compilation errors.
type UnsafeGithubProviderServer interface {
	mustEmbedUnimplementedGithubProviderServer()
}

func RegisterGithubProviderServer(s grpc.ServiceRegistrar, srv GithubProviderServer) {
	// If the following call panics, it indicates UnimplementedGithubProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GithubProvider_ServiceDesc, srv)
}

func _GithubProvider_FetchPR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubProviderServer).FetchPR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GithubProvider_FetchPR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubProviderServer).FetchPR(ctx, req.(*FetchPRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GithubProvider_ServiceDesc is the grpc.ServiceDesc for GithubProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GithubProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github_provider.GithubProvider",
	HandlerType: (*GithubProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchPR",
			Handler:    _GithubProvider_FetchPR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github_provider.proto",
}
