version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=cedille_user
      - POSTGRES_PASSWORD=cedille_pwd
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./scripts/postgres/:/docker-entrypoint-initdb.d/

volumes:
  postgres:
    driver: local