version: '3'

services:
  email_provider:
    build:
      context: .
      dockerfile: ./cmd/email-provider/Dockerfile
    container_name: email_provider
    ports:
      - 4000:4000
    expose:
      - 4000
    networks:
      - microservices
    environment:
      EMAIL_FROM_ADDRESS: noreply@cedille.club
      EMAIL_FROM_NAME: cedille
      EMAIL_NAME_TO: cedille
      EMAIL_TO_ADDRESS: cedille@etsmtl.net
      EMAIL_SUBJECT: email_subject
      EMAIL_SMTP_API_KEY: ${EMAIL_SMTP_API_KEY}
    entrypoint: [
      "/email_provider",
      "--port", "4000", 
    ]

  discord_provider:
    build:
      context: .
      dockerfile: ./cmd/discord-provider/Dockerfile
    container_name: discord_provider
    ports:
      - 5000:5000
    expose:
      - 5000
    networks:
      - microservices
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
    entrypoint: [
      "/discord_provider",
      "--port", "5000", 
    ]

  calidum_rotae_service:
    build:
      context: .
      dockerfile: ./cmd/calidum-rotae-service/Dockerfile
    container_name: calidum_rotae_service
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - microservices
    depends_on:
      - email_provider
      - discord_provider
    environment:
      CALIDUM_ROTAE_SERVICE_API_KEY: ${CALIDUM_ROTAE_SERVICE_API_KEY}
    entrypoint: [
      "/calidum_rotae_service",
      "--port", "3000",
      "--discord_provider_hostname", "discord_provider",
      "--discord_provider_port", "5000",
      "--email_provider_hostname", "email_provider",
      "--email_provider_port", "4000",
      "--otel_otlp_exporter_host", "localhost",
      "--otel_otlp_exporter_port", "4318",
      "--allowed_domains", "http://localhost*",
    ]
    
networks:
  microservices:
