version: '3'

services:
  postgres:
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=cedille_user
      - POSTGRES_PASSWORD=cedille_pwd
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./scripts/postgres/:/docker-entrypoint-initdb.d/

  email_provider:
    build:
      context: .
      dockerfile: ./cmd/email-provider/Dockerfile
    container_name: email_provider
    ports:
      - 4000:4000
    expose:
      - 4000
    networks:
      - microservices
    environment:
      EMAIL_FROM_ADDRESS: email_from_address
      EMAIL_FROM_NAME: email_from_name
      EMAIL_NAME_TO: email_to_name
      EMAIL_TO_ADDRESS: email_to_address
      EMAIL_SUBJECT: email_subject
      EMAIL_SENDGRID_API_KEY: email_sendgrid_api_key
    entrypoint: [
      "/email_provider",
      "--port", "4000", 
    ]

  discord_provider:
    build:
      context: .
      dockerfile: ./cmd/discord-provider/Dockerfile
    container_name: discord_provider
    ports:
      - 5000:5000
    expose:
      - 5000
    networks:
      - microservices
    environment:
      DISCORD_WEBHOOK_URL: discord_webhook
    entrypoint: [
      "/discord_provider",
      "--port", "5000", 
    ]

  calidum_rotae_service:
    build:
      context: .
      dockerfile: ./cmd/calidum-rotae-service/Dockerfile
    container_name: calidum_rotae_service
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - microservices
    depends_on:
      - email_provider
      - discord_provider
    environment:
      DB_PASSWORD: cedille_pwd
      CALIDUM_ROTAE_SERVICE_API_KEY: 1234
    entrypoint: [
      "/calidum_rotae_service",
      "--port", "3000",
      "--discord_provider_port", "5000",
      "--email_provider_port", "4000",
      "--db-user", "cedille_user",
      "--db-name", "calidum_rotae"
    ]
    
networks:
  microservices:

volumes:
  postgres:
    driver: local