// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: discord_provider.proto

package discord_provider

import (
	provider "github.com/clubcedille/calidum-rotae-backend/pkg/proto-gen/provider"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sender         *provider.Requester    `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	RequestService string                 `protobuf:"bytes,2,opt,name=RequestService,proto3" json:"RequestService,omitempty"`
	RequestDetails string                 `protobuf:"bytes,3,opt,name=RequestDetails,proto3" json:"RequestDetails,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_discord_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discord_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_discord_provider_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetSender() *provider.Requester {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *SendMessageRequest) GetRequestService() string {
	if x != nil {
		return x.RequestService
	}
	return ""
}

func (x *SendMessageRequest) GetRequestDetails() string {
	if x != nil {
		return x.RequestDetails
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_discord_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discord_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_discord_provider_proto_rawDescGZIP(), []int{1}
}

var File_discord_provider_proto protoreflect.FileDescriptor

const file_discord_provider_proto_rawDesc = "" +
	"\n" +
	"\x16discord_provider.proto\x12\x10discord_provider\x1a\x0eprovider.proto\"\x91\x01\n" +
	"\x12SendMessageRequest\x12+\n" +
	"\x06Sender\x18\x01 \x01(\v2\x13.provider.RequesterR\x06Sender\x12&\n" +
	"\x0eRequestService\x18\x02 \x01(\tR\x0eRequestService\x12&\n" +
	"\x0eRequestDetails\x18\x03 \x01(\tR\x0eRequestDetails\"\x15\n" +
	"\x13SendMessageResponse2m\n" +
	"\x0fDiscordProvider\x12Z\n" +
	"\vSendMessage\x12$.discord_provider.SendMessageRequest\x1a%.discord_provider.SendMessageResponseB^Z\\github.com/clubcedille/calidum-rotae-backend/pkg/proto-gen/discord-provider;discord_providerb\x06proto3"

var (
	file_discord_provider_proto_rawDescOnce sync.Once
	file_discord_provider_proto_rawDescData []byte
)

func file_discord_provider_proto_rawDescGZIP() []byte {
	file_discord_provider_proto_rawDescOnce.Do(func() {
		file_discord_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discord_provider_proto_rawDesc), len(file_discord_provider_proto_rawDesc)))
	})
	return file_discord_provider_proto_rawDescData
}

var file_discord_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_discord_provider_proto_goTypes = []any{
	(*SendMessageRequest)(nil),  // 0: discord_provider.SendMessageRequest
	(*SendMessageResponse)(nil), // 1: discord_provider.SendMessageResponse
	(*provider.Requester)(nil),  // 2: provider.Requester
}
var file_discord_provider_proto_depIdxs = []int32{
	2, // 0: discord_provider.SendMessageRequest.Sender:type_name -> provider.Requester
	0, // 1: discord_provider.DiscordProvider.SendMessage:input_type -> discord_provider.SendMessageRequest
	1, // 2: discord_provider.DiscordProvider.SendMessage:output_type -> discord_provider.SendMessageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_discord_provider_proto_init() }
func file_discord_provider_proto_init() {
	if File_discord_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discord_provider_proto_rawDesc), len(file_discord_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discord_provider_proto_goTypes,
		DependencyIndexes: file_discord_provider_proto_depIdxs,
		MessageInfos:      file_discord_provider_proto_msgTypes,
	}.Build()
	File_discord_provider_proto = out.File
	file_discord_provider_proto_goTypes = nil
	file_discord_provider_proto_depIdxs = nil
}
