// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: cluster_provider.proto

package cluster_provider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterProvider_GetUserResources_FullMethodName = "/cluster_provider.ClusterProvider/GetUserResources"
)

// ClusterProviderClient is the client API for ClusterProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterProviderClient interface {
	// Gets K8s Cluster data for a specified user
	GetUserResources(ctx context.Context, in *UserResourceRequest, opts ...grpc.CallOption) (*GetUserResourcesResponse, error)
}

type clusterProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterProviderClient(cc grpc.ClientConnInterface) ClusterProviderClient {
	return &clusterProviderClient{cc}
}

func (c *clusterProviderClient) GetUserResources(ctx context.Context, in *UserResourceRequest, opts ...grpc.CallOption) (*GetUserResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResourcesResponse)
	err := c.cc.Invoke(ctx, ClusterProvider_GetUserResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterProviderServer is the server API for ClusterProvider service.
// All implementations must embed UnimplementedClusterProviderServer
// for forward compatibility.
type ClusterProviderServer interface {
	// Gets K8s Cluster data for a specified user
	GetUserResources(context.Context, *UserResourceRequest) (*GetUserResourcesResponse, error)
	mustEmbedUnimplementedClusterProviderServer()
}

// UnimplementedClusterProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterProviderServer struct{}

func (UnimplementedClusterProviderServer) GetUserResources(context.Context, *UserResourceRequest) (*GetUserResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserResources not implemented")
}
func (UnimplementedClusterProviderServer) mustEmbedUnimplementedClusterProviderServer() {}
func (UnimplementedClusterProviderServer) testEmbeddedByValue()                         {}

// UnsafeClusterProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterProviderServer will
// result in compilation errors.
type UnsafeClusterProviderServer interface {
	mustEmbedUnimplementedClusterProviderServer()
}

func RegisterClusterProviderServer(s grpc.ServiceRegistrar, srv ClusterProviderServer) {
	// If the following call panics, it indicates UnimplementedClusterProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterProvider_ServiceDesc, srv)
}

func _ClusterProvider_GetUserResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterProviderServer).GetUserResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterProvider_GetUserResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterProviderServer).GetUserResources(ctx, req.(*UserResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterProvider_ServiceDesc is the grpc.ServiceDesc for ClusterProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cluster_provider.ClusterProvider",
	HandlerType: (*ClusterProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserResources",
			Handler:    _ClusterProvider_GetUserResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster_provider.proto",
}
