// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cluster_provider.proto

package cluster_provider

import (
	_ "github.com/clubcedille/calidum-rotae-backend/pkg/proto-gen/provider"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUID       string                 `protobuf:"bytes,1,opt,name=UserUID,proto3" json:"UserUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResourceRequest) Reset() {
	*x = UserResourceRequest{}
	mi := &file_cluster_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResourceRequest) ProtoMessage() {}

func (x *UserResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResourceRequest.ProtoReflect.Descriptor instead.
func (*UserResourceRequest) Descriptor() ([]byte, []int) {
	return file_cluster_provider_proto_rawDescGZIP(), []int{0}
}

func (x *UserResourceRequest) GetUserUID() string {
	if x != nil {
		return x.UserUID
	}
	return ""
}

type GetUserResourcesResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserResourcesResponse string                 `protobuf:"bytes,1,opt,name=UserResourcesResponse,proto3" json:"UserResourcesResponse,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetUserResourcesResponse) Reset() {
	*x = GetUserResourcesResponse{}
	mi := &file_cluster_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResourcesResponse) ProtoMessage() {}

func (x *GetUserResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResourcesResponse.ProtoReflect.Descriptor instead.
func (*GetUserResourcesResponse) Descriptor() ([]byte, []int) {
	return file_cluster_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResourcesResponse) GetUserResourcesResponse() string {
	if x != nil {
		return x.UserResourcesResponse
	}
	return ""
}

var File_cluster_provider_proto protoreflect.FileDescriptor

const file_cluster_provider_proto_rawDesc = "" +
	"\n" +
	"\x16cluster_provider.proto\x12\x10cluster_provider\x1a\x0eprovider.proto\"/\n" +
	"\x13UserResourceRequest\x12\x18\n" +
	"\aUserUID\x18\x01 \x01(\tR\aUserUID\"P\n" +
	"\x18GetUserResourcesResponse\x124\n" +
	"\x15UserResourcesResponse\x18\x01 \x01(\tR\x15UserResourcesResponse2x\n" +
	"\x0fClusterProvider\x12e\n" +
	"\x10GetUserResources\x12%.cluster_provider.UserResourceRequest\x1a*.cluster_provider.GetUserResourcesResponseB^Z\\github.com/clubcedille/calidum-rotae-backend/pkg/proto-gen/cluster-provider;cluster_providerb\x06proto3"

var (
	file_cluster_provider_proto_rawDescOnce sync.Once
	file_cluster_provider_proto_rawDescData []byte
)

func file_cluster_provider_proto_rawDescGZIP() []byte {
	file_cluster_provider_proto_rawDescOnce.Do(func() {
		file_cluster_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_provider_proto_rawDesc), len(file_cluster_provider_proto_rawDesc)))
	})
	return file_cluster_provider_proto_rawDescData
}

var file_cluster_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cluster_provider_proto_goTypes = []any{
	(*UserResourceRequest)(nil),      // 0: cluster_provider.UserResourceRequest
	(*GetUserResourcesResponse)(nil), // 1: cluster_provider.GetUserResourcesResponse
}
var file_cluster_provider_proto_depIdxs = []int32{
	0, // 0: cluster_provider.ClusterProvider.GetUserResources:input_type -> cluster_provider.UserResourceRequest
	1, // 1: cluster_provider.ClusterProvider.GetUserResources:output_type -> cluster_provider.GetUserResourcesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cluster_provider_proto_init() }
func file_cluster_provider_proto_init() {
	if File_cluster_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_provider_proto_rawDesc), len(file_cluster_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_provider_proto_goTypes,
		DependencyIndexes: file_cluster_provider_proto_depIdxs,
		MessageInfos:      file_cluster_provider_proto_msgTypes,
	}.Build()
	File_cluster_provider_proto = out.File
	file_cluster_provider_proto_goTypes = nil
	file_cluster_provider_proto_depIdxs = nil
}
