// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: shell_provider.proto

package shell_provider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestCommand string                 `protobuf:"bytes,1,opt,name=RequestCommand,proto3" json:"RequestCommand,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_shell_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shell_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_shell_provider_proto_rawDescGZIP(), []int{0}
}

func (x *SendCommandRequest) GetRequestCommand() string {
	if x != nil {
		return x.RequestCommand
	}
	return ""
}

type SendCommandResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommandResponse string                 `protobuf:"bytes,1,opt,name=CommandResponse,proto3" json:"CommandResponse,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendCommandResponse) Reset() {
	*x = SendCommandResponse{}
	mi := &file_shell_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponse) ProtoMessage() {}

func (x *SendCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shell_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponse) Descriptor() ([]byte, []int) {
	return file_shell_provider_proto_rawDescGZIP(), []int{1}
}

func (x *SendCommandResponse) GetCommandResponse() string {
	if x != nil {
		return x.CommandResponse
	}
	return ""
}

var File_shell_provider_proto protoreflect.FileDescriptor

const file_shell_provider_proto_rawDesc = "" +
	"\n" +
	"\x14shell_provider.proto\x12\x0eshell_provider\"<\n" +
	"\x12SendCommandRequest\x12&\n" +
	"\x0eRequestCommand\x18\x01 \x01(\tR\x0eRequestCommand\"?\n" +
	"\x13SendCommandResponse\x12(\n" +
	"\x0fCommandResponse\x18\x01 \x01(\tR\x0fCommandResponse2g\n" +
	"\rShellProvider\x12V\n" +
	"\vSendCommand\x12\".shell_provider.SendCommandRequest\x1a#.shell_provider.SendCommandResponseBZZXgithub.com/clubcedille/calidum-rotae-backend/pkg/proto-gen/shell-provider;shell_providerb\x06proto3"

var (
	file_shell_provider_proto_rawDescOnce sync.Once
	file_shell_provider_proto_rawDescData []byte
)

func file_shell_provider_proto_rawDescGZIP() []byte {
	file_shell_provider_proto_rawDescOnce.Do(func() {
		file_shell_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shell_provider_proto_rawDesc), len(file_shell_provider_proto_rawDesc)))
	})
	return file_shell_provider_proto_rawDescData
}

var file_shell_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shell_provider_proto_goTypes = []any{
	(*SendCommandRequest)(nil),  // 0: shell_provider.SendCommandRequest
	(*SendCommandResponse)(nil), // 1: shell_provider.SendCommandResponse
}
var file_shell_provider_proto_depIdxs = []int32{
	0, // 0: shell_provider.ShellProvider.SendCommand:input_type -> shell_provider.SendCommandRequest
	1, // 1: shell_provider.ShellProvider.SendCommand:output_type -> shell_provider.SendCommandResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shell_provider_proto_init() }
func file_shell_provider_proto_init() {
	if File_shell_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shell_provider_proto_rawDesc), len(file_shell_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shell_provider_proto_goTypes,
		DependencyIndexes: file_shell_provider_proto_depIdxs,
		MessageInfos:      file_shell_provider_proto_msgTypes,
	}.Build()
	File_shell_provider_proto = out.File
	file_shell_provider_proto_goTypes = nil
	file_shell_provider_proto_depIdxs = nil
}
