// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: shell_provider.proto

package shell_provider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShellProvider_SendCommand_FullMethodName = "/shell_provider.ShellProvider/SendCommand"
)

// ShellProviderClient is the client API for ShellProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShellProviderClient interface {
	// SendCommand sends a command to a fake shell
	SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error)
}

type shellProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewShellProviderClient(cc grpc.ClientConnInterface) ShellProviderClient {
	return &shellProviderClient{cc}
}

func (c *shellProviderClient) SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCommandResponse)
	err := c.cc.Invoke(ctx, ShellProvider_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShellProviderServer is the server API for ShellProvider service.
// All implementations must embed UnimplementedShellProviderServer
// for forward compatibility.
type ShellProviderServer interface {
	// SendCommand sends a command to a fake shell
	SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error)
	mustEmbedUnimplementedShellProviderServer()
}

// UnimplementedShellProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShellProviderServer struct{}

func (UnimplementedShellProviderServer) SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedShellProviderServer) mustEmbedUnimplementedShellProviderServer() {}
func (UnimplementedShellProviderServer) testEmbeddedByValue()                       {}

// UnsafeShellProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShellProviderServer will
// result in compilation errors.
type UnsafeShellProviderServer interface {
	mustEmbedUnimplementedShellProviderServer()
}

func RegisterShellProviderServer(s grpc.ServiceRegistrar, srv ShellProviderServer) {
	// If the following call panics, it indicates UnimplementedShellProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShellProvider_ServiceDesc, srv)
}

func _ShellProvider_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShellProviderServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShellProvider_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShellProviderServer).SendCommand(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShellProvider_ServiceDesc is the grpc.ServiceDesc for ShellProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShellProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shell_provider.ShellProvider",
	HandlerType: (*ShellProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _ShellProvider_SendCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shell_provider.proto",
}
