// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: email_provider.proto

package email_provider

import (
	provider "github.com/clubcedille/calidum-rotae-backend/pkg/proto-gen/provider"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sender         *provider.Requester    `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	RequestService string                 `protobuf:"bytes,2,opt,name=RequestService,proto3" json:"RequestService,omitempty"`
	RequestDetails string                 `protobuf:"bytes,3,opt,name=RequestDetails,proto3" json:"RequestDetails,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_email_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_email_provider_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetSender() *provider.Requester {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *SendEmailRequest) GetRequestService() string {
	if x != nil {
		return x.RequestService
	}
	return ""
}

func (x *SendEmailRequest) GetRequestDetails() string {
	if x != nil {
		return x.RequestDetails
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_email_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_email_provider_proto_rawDescGZIP(), []int{1}
}

var File_email_provider_proto protoreflect.FileDescriptor

const file_email_provider_proto_rawDesc = "" +
	"\n" +
	"\x14email_provider.proto\x12\x0eemail_provider\x1a\x0eprovider.proto\"\x8f\x01\n" +
	"\x10SendEmailRequest\x12+\n" +
	"\x06Sender\x18\x01 \x01(\v2\x13.provider.RequesterR\x06Sender\x12&\n" +
	"\x0eRequestService\x18\x02 \x01(\tR\x0eRequestService\x12&\n" +
	"\x0eRequestDetails\x18\x03 \x01(\tR\x0eRequestDetails\"\x13\n" +
	"\x11SendEmailResponse2a\n" +
	"\rEmailProvider\x12P\n" +
	"\tSendEmail\x12 .email_provider.SendEmailRequest\x1a!.email_provider.SendEmailResponseBZZXgithub.com/clubcedille/calidum-rotae-backend/pkg/proto-gen/email-provider;email_providerb\x06proto3"

var (
	file_email_provider_proto_rawDescOnce sync.Once
	file_email_provider_proto_rawDescData []byte
)

func file_email_provider_proto_rawDescGZIP() []byte {
	file_email_provider_proto_rawDescOnce.Do(func() {
		file_email_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_provider_proto_rawDesc), len(file_email_provider_proto_rawDesc)))
	})
	return file_email_provider_proto_rawDescData
}

var file_email_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_email_provider_proto_goTypes = []any{
	(*SendEmailRequest)(nil),   // 0: email_provider.SendEmailRequest
	(*SendEmailResponse)(nil),  // 1: email_provider.SendEmailResponse
	(*provider.Requester)(nil), // 2: provider.Requester
}
var file_email_provider_proto_depIdxs = []int32{
	2, // 0: email_provider.SendEmailRequest.Sender:type_name -> provider.Requester
	0, // 1: email_provider.EmailProvider.SendEmail:input_type -> email_provider.SendEmailRequest
	1, // 2: email_provider.EmailProvider.SendEmail:output_type -> email_provider.SendEmailResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_email_provider_proto_init() }
func file_email_provider_proto_init() {
	if File_email_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_provider_proto_rawDesc), len(file_email_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_email_provider_proto_goTypes,
		DependencyIndexes: file_email_provider_proto_depIdxs,
		MessageInfos:      file_email_provider_proto_msgTypes,
	}.Build()
	File_email_provider_proto = out.File
	file_email_provider_proto_goTypes = nil
	file_email_provider_proto_depIdxs = nil
}
