@startuml calidum-rotae

node DiscordAPI as "Discord API" {
 	component DiscordAPIComponent
}

node MattermostAPI as "Mattermost API" {
 	component MattermostAPIComponent
}

node Email as "Email Sender" {
 	component EmailSenderComponent
}

node Data as "Google Cloud SQL" {
	database Database as "Postgres DB" {
	}
}

cloud Cluster as "Cluster" {
	component CalidumRotaeService
	component Frontend
	interface " " as AP
	
	Frontend -d(0)-> CalidumRotaeService : POST HTTP Request

	'1) Discord Provider -> calls Discord API
	'2) Mattermost Provider -> calls Mattermost API
	'3) Email Provider -> calls email (i.e.: mailgun) API

	component DiscordProvider
	component MattermostProvider
	component EmailProvider

	AP --> DiscordProvider
	AP --> MattermostProvider
	AP --> EmailProvider 

 	AP )- [CalidumRotaeService]
}

CalidumRotaeService --> Database
DiscordProvider --> DiscordAPIComponent  : HTTPS
MattermostProvider --> MattermostAPIComponent  : HTTPS
EmailProvider --> EmailSenderComponent  : HTTPS

@enduml