@startuml calidum-rotae

node DiscordAPI as "Discord API" {
 	component DiscordAPIComponent
}

node Email as "Email Sender" {
 	component EmailSenderComponent
}

node Data as "Google Cloud SQL" {
	database Database as "Postgres DB" {
	}
}

cloud Cluster as "Cluster" {
	component CalidumRotaeService
	component Frontend
	interface " " as AP
	
	Frontend -d(0)-> CalidumRotaeService : POST HTTP Request

	'1) Discord Provider -> calls Discord API
	'2) Email Provider -> calls email (i.e.: mailgun) API

	component DiscordProvider
	component EmailProvider

	AP --> DiscordProvider : gRPC
	AP --> EmailProvider : gRPC

 	AP )- [CalidumRotaeService]
}

CalidumRotaeService --> Database
DiscordProvider --> DiscordAPIComponent  : HTTPS
EmailProvider --> EmailSenderComponent  : HTTPS

@enduml