name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-scan:
    uses: clubcedille/cedille-workflows/.github/workflows/build-and-scan.yaml@master
    with:
      project-key: calidum-rotae
      project-name: Calidum Rotae
      build-command: npm ci && npm run build
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
